AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  intro

  Sample SAM Template for intro

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ClockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: clock/
      Handler: handler.clock
      Runtime: python3.9
      Events:
        ClockAPI:
          Type: Api
          Properties:
            Path: /clock
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClockAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/clock/"
  ClockFunction:
    Description: Clock Lambda Function ARN"
    Value: !GetAtt ClockFunction.Arn
  ClockFunctionIamRole:
    Description: "Implicit IAM Role created for Clock function"
    Value: !GetAtt ClockFunction.Arn
